config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :reviews
  resources :books do
    resources :reviews, only: [:new, :create, :update]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
get "/login", to: "sessions#new", as: "login"
get "/logout", to: "sessions#destroy"
delete "/logout", to: "sessions#destroy"

resources :sessions, only: [:create]
end

app/models/BookApi.rb
class BookApi

    def self.fetch
        response = HTTP.get("https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=YpppMZ9kyOW4ONAii0MLeGCVH5ExmtHT")
        books = JSON.parse(response)["results"]["books"]
        books.each do |book|
          Book.create(title: book["title"], genre: book["publisher"], author: book["author"], years_published: book["rank"])
        end
        
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews

    scope :search_by_title, ->(title) {where("title like ?", "%#{title}%")}
    
    def titleize
        self.split(" ").map{|word| word.capitiaze}.join(" ")
    end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :reviews
    has_many :books, through: :reviews 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user

    def logged_in?
        !!current_user
    end

    def current_user
        if session[:user_id]
        User.find(session[:user_id])
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    def index
        @books = Book.all
        if params[:search]
         @books = @books.search_by_title(params[:search]) 
        end
       
    end

    def new
        @book = Book.new
    end

    def create
       book = Book.create(book_params)
       redirect_to book
    end
    def show
        @review = Review.new
        @book = Book.find(params[:id])
    end

    def edit
        
    end

    def update
       @book.update(book_params)
       redirect_to(book_params)
    end


    def destroy
    
      @book.destroy
      redirect_to books_path
    end

    private 

    def set_book
        @book = Book.find(params[:id])

    end

    def book_params
        params.require(:book).permit(:title,  :genre, :author, :years_published)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_review, only: [:show, :update, :destroy]
before_action :set_books, only: [:create]
    def create 
        @review = @book.reviews.build(review_params)
        @review.user = current_user
        if @review.save
            redirect_to @book
        else
           render :"books/show"
        end
    end
    def show
    end
    def edit
    end

    def update
        if @review.update(review_params)
            redirect_to @review.book
        else
            render :edit
        end
    end

    def destroy
        @review.destroy
        redirect_to books_path
    end

    private
    def set_review
        @review = Review.find(params[:id])
    end
   
    def set_books
     @book = Book.find(params[:book_id]) if params[:book_id]
    end

    def review_params
        params.require(:review).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
   end


  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to books_path
  
    else
      flash[:errors] = ["Invalid Username or Password!"]
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to books_path
        else
            render :new
        end
      
    end

    private

    def user_params
        params.require(:user).permit(:name, :password, :password_confirmation, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %><br>
    <%= f.label :author %><br>
    <%= f.text_field :author %><br>
    <%= f.label :years_published %><br>
    <%= f.number_field :years_published, in: (1800..Date.current.year) %><br>
    <%= f.submit %>
  <% end %>

app/views/books/edit.html.erb
<h1> Edit <%= @book.title %> </h1>

<%= render "form" %>

app/views/books/index.html.erb
<h1> Here's All Books </h1>
<%= form_tag books_path, method: :get do %>
    <%= label_tag :search, "Search Books" %>
    <%= text_field_tag :search, params[:search] %>
   <%= submit_tag "search"%>
    <% end %>
<ul>
<% @books.each do |book|%>
    <%= link_to book.title.titleize, book_path(book)  %>
    <% end %>
</ul>

<%= link_to "ADD BOOK", new_book_path, method: :get %>

app/views/books/new.html.erb
<h1>ADD Book</h1>

<%= render "form" %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h3>By <%= @book.author %></h3>
<p>Genre: <%= @book.genre %></p>
<p>Years Published: <%= @book.years_published %></p>


<%= form_for [@book, @review] do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content, cols: 30, rows: 10 %>
    <%= f.submit  %>
    <% end %>
    <% @book.reviews.each do |review|%>
         <p> Review: <%= review.content %></p>
        <p> Name: <%= review.user.name %></p>
          <%= button_to "Edit Review", edit_review_path(review), method: :get %><br>
          <%= button_to "Delete Review", review, method: :delete %>
         <% end %>
       

<%= link_to "Edit #{@book.title.titleize}", edit_book_path(@book), method: :get %>

<%= button_to "Shred #{@book.title}", book_path, method: :delete %>

app/views/layouts/_nav.html.erb
<nav>
<% if logged_in? %>
<%= link_to "All Books", books_path %>
<h1> Welcome <%= current_user.name %>
<%= link_to "logout", logout_path, method: "delete" %>
<% else %>
   

<%= link_to "Sign Up", new_user_path %>

<% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "/layouts/nav" %>
    <%= yield %>
  </body>
</html>

app/views/reviews/_review.html.erb
<p>Review: <%= review.content %></p>
<p> Name: <%= review.user.name %></p>

app/views/reviews/edit.html.erb
<%= form_for [@book, @review] do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content, cols: 30, rows: 10 %>
    <%= f.submit  %>
    <% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
     <%= f.label :age %>
    <%= f.number_field :age %>
    <%= f.submit "sign_up"%>
<% end %>